### ISSUE TITLE
Backslash not working

### ISSUE THREAD

**Issue by KarimGeiger** [SimpleRegex/SRL-JavaScript#14]
Hi,

I was just updating the test rules in PR #13 and it seems like the [backslash rule](https://github.com/SimpleRegex/Test-Rules/blob/594659ac8f9e1623fa5576447befe3d4616fc74f/backslash.rule) fails:

https://travis-ci.org/SimpleRegex/SRL-JavaScript/builds/264277712?utm_source=github_status&utm_medium=notification

**Comment by corsonknowles** [comment]
Thanks, I just pushed a commit that will double escape backslash, which should restore it to working order
