### ISSUE TITLE
Capture group name assignment fails with  TypeError: Cannot read property 'slice' of null

### ISSUE THREAD

**Issue by myAlterX** [SimpleRegex/SRL-JavaScript#17]
Hi,
Not sure if you are still maintaining this project, but is seems like a great way to simplify the use of RegExp. Congrats.
I found a problem where I'm running several strings through a match and if nothing matches, result is null which results in an error in the following line:

        return Array.prototype.reduce.call(result.slice(1), (result, current, index) => {

However I understand this is a workaround implementation for named captures which is now a part of the ECMAScript spec, so not sure if placing a check is the right move or simply to support named matches natively.

**Comment by teabyii** [comment]
![image](https://user-images.githubusercontent.com/4496552/73810866-c3371680-4812-11ea-86ae-efdb2a3476de.png)
I don't think it is a good time to use native named capture groups.
And if you can provide a simple test case for the error, I will add `null` check in this method to avoid it.

**Comment by myAlterX** [comment]
You are right of course! I was developing in node and didn't think about browser compliance. Sorry.
In regards to the `null` check, here is the repro:

```javascript
   let query = new SRL("capture (literally 'TEST') as test")
   let match = query.getMatch('WORD NOT HERE')
```

Thanks again!
