### ISSUE TITLE
.exec() return only first result

### ISSUE THREAD

**Issue by GeekEdem** [SimpleRegex/SRL-JavaScript#3]
Hello. I have issue with returning all results to variable in JS. I build simple [test](https://simple-regex.com/build/57e4f3bc78e82), but when use

```
const SRL = require('srl');
const query = new SRL(query);
console.log(query.exec(query));
```

In console recieve:

```
[ 'What',
  'What',
  index: 0,
  input: 'What is Lorem Ipsum? ... ' ]
```

But what about all other? And why `What` is 2 times?
Thanks.

**Comment by teabyii** [comment]
In JavaScript, Regex is always take the 'first-match', but not all, unless given the `g` flag.

In this case, you should use like this: `query.all().exec('...')` .

And I will make a commit to take a keyword like `global` in the interpreter later for SRL-JavaScript to add `g` flag.

About the `exec`, if you want to take all results matched in a regex with `g` flag, you should use a loop like:

``` js
const myRe = /ab*/g;
const str = 'abbcdefabh';
let myArray;
while ((myArray = myRe.exec(str)) !== null) {
  var msg = 'Found ' + myArray[0] + '. ';
  msg += 'Next match starts at ' + myRe.lastIndex;
  console.log(msg);
}
```

More details: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/exec

**Comment by KarimGeiger** [comment]
I'm not sure if I completely understand the problem, but wouldn't it be a good idea to apply the `g` flag as a default? Would that break anything?

**Comment by teabyii** [comment]
To apply the `g` flag as a default will not break something, maybe a little performance loss.
I don't think it is a good idea, since it's always non-global in JavaScript. When you need in some cases, then apply `g` flag.

**Comment by KarimGeiger** [comment]
Nevertheless it'd break the current SRL "standard"... How's the default behaviour in other programming languages like @SimpleRegex/java-devs or @SimpleRegex/python-devs? And, is the `g` flag supported there?

**Comment by teabyii** [comment]
En ... It's a problem. I think we should have a idea for SRL "standard" to deal with differences in different languages.

**Comment by GeekEdem** [comment]
jsenjoy, thanks for your fast responce.
The problem is not resolved with SRL implementation.
When I use:

```
const SRL = require('srl');
var srlQuery = "capture(uppercase letter, no whitespace, any character once or more)";
const query = new SRL(srlQuery);
console.log(query.all().exec(text));
```

Nothing is changed:

```
[ 'What',
  'What',
  index: 0,
  input: 'What is Lorem Ipsum? ... ' ]
```

In second example you use not SRL, but default Regex. When I try to make this with SRL:

```
const SRL = require('srl');
var srlQuery = "capture(uppercase letter, no whitespace, any character once or more)";
const query = new SRL(srlQuery);
var myArray;
while ((myArray = query.exec(text)) !== null) {
     console.log(myArray);
}
```

I receive infinity loop, what prints in console all time the same thing:

```
[ 'What',
  'What',
  index: 0,
  input: 'What is Lorem Ipsum? ... ' ]
```

So, this 2 methods not work to get all results.
Thanks.

**Comment by teabyii** [comment]
I am so sorry to confuse you. You should use flag `g` and loop, both of them, like this:

``` js
const SRL = require('srl');
var srlQuery = "capture(uppercase letter, no whitespace, any character once or more)";
const query = new SRL(srlQuery).all(); // Use all() method here.

var myArray;
while ((myArray = query.exec(text)) !== null) {
     console.log(myArray);
}
```

**Comment by teabyii** [comment]
@KarimGeiger I think I will make `g` flag as default to follow the SRL "standard" and leave more  description  about it in "README", unless there is a better way to solve.

**Comment by teabyii** [comment]
@GeekEdem I publish 0.2.0 to give more methods to use regex conveniently, you can upgrade package and check it out: https://github.com/SimpleRegex/SRL-JavaScript#additional

**Comment by SamTebbs33** [comment]
We have yet to decide a default in the Java implementation, perhaps we'll go with "g" as default too.

**Comment by GeekEdem** [comment]
Oh, its great! Thank you very much!
